//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Text
	{
		private String tag;
		private String content;

		public Text ()
		{
		}

		public void setTag(string s){
			tag = s;
		}

		public void setContent(string s){
			content = s;
		}

		public string getTag(){
			return tag;
		}

		public string getContent(){
			return tag;
		}
	}


}

